config/routes.rb
UserSubmission::Application.routes.draw do
  match "submissions/admin"
  resources :submissions
  root :to => 'submissions#index'
end

app/models/submission.rb
class Submission < ActiveRecord::Base
  
  if Rails.env.development?
    ENV = YAML.load(File.read("#{Rails.root}/config/s3.yml"))
  end

  has_attached_file :photo, 
    :styles => {:medium => "500x500>", :thumb => "300x300>"},
    :storage => :s3,
    :bucket => (Rails.env.production? ? 'typecurio' : 'typecurio-testing'),
    :s3_credentials => {
      :access_key_id => ENV['S3_KEY'],
      :secret_access_key => ENV['S3_SECRET'] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  # GET /submissions
  # GET /submissions.json
  def index
    @submissions = Submission.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @submissions }
    end
  end

  # GET /submissions/1
  # GET /submissions/1.json
  def show
    @submission = Submission.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @submission }
    end
  end

  # GET /submissions/new
  # GET /submissions/new.json
  def new
    @submission = Submission.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @submission }
    end
  end

  # GET /submissions/1/edit
  def edit
    @submission = Submission.find(params[:id])
  end

  # POST /submissions
  # POST /submissions.json
  def create
    @submission = Submission.new(params[:submission])

    respond_to do |format|
      if @submission.save
        format.html { redirect_to @submission, notice: 'Submission was successfully created.' }
        format.json { render json: @submission, status: :created, location: @submission }
      else
        format.html { render action: "new" }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /submissions/1
  # PUT /submissions/1.json
  def update
    @submission = Submission.find(params[:id])

    respond_to do |format|
      if @submission.update_attributes(params[:submission])
        format.html { redirect_to @submission, notice: 'Submission was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /submissions/1
  # DELETE /submissions/1.json
  def destroy
    @submission = Submission.find(params[:id])
    @submission.destroy

    respond_to do |format|
      format.html { redirect_to submissions_url }
      format.json { head :no_content }
    end
  end

  def admin
    @submissions = Submission.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def url_with_protocol(url)
    /^http/.match(url) ? url : "http://#{url}"
  end
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>//TYPECURIO\\</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <script type="text/javascript" src="http://use.typekit.com/bhl2buy.js"></script>
  <script type="text/javascript">try{Typekit.load();}catch(e){}</script>

  <%= csrf_meta_tags %>

</head>
<body>
  <div id="header">
    <div id="skipmenu">
      <h2>
        <%= link_to "TYPE CURIO", root_url %>

        <hr id="hrule" />

        <div id="subtext">foraging for type</div>
      </h2>
    </div>
  </div>


  <div id="mainnav">
  <ul>
    <li><%= link_to "Home", root_url %></li>
    <li><a href="#">About</a></li>
    <li><a href="#">Popular</a></li>
    <li><a href="#">Blog</a></li>
    <li><%= link_to "Contribute", new_submission_path %></li>
  </ul>
  </div>

<%= yield %>


  <div id="footer">
    © TypeCurio 2010, All Rights Reserved
  </div>
</body>
</html>

app/views/submissions/_form.html.erb
<%= form_for(@submission, :html => {:multipart => true }) do |f| %>
  <% if @submission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@submission.errors.count, "error") %> prohibited this submission from being saved:</h2>

      <ul>
      <% @submission.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :blurb %><br />
    <%= f.text_field :blurb %>
  </div>
  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label "Upload photo"%><br />
    <%= f.file_field :photo %>
  </div> 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/submissions/admin.html.erb
<h1>Listing submissions</h1>

<%= link_to 'New Submission', new_submission_path %>

<table>
  <tr>
    <th>Title</th>
    <th>Blurb</th>
    <th>Link</th>
    <th>Photo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @submissions.each do |submission| %>
  <tr>
    <td><%= submission.title %></td>
    <td><%= submission.blurb %></td>
    <td><%= submission.link %></td>
    <td><%= image_tag submission.photo.url(:thumb) %></td>
    <td><%= link_to 'Show', submission %></td>
    <td><%= link_to 'Edit', edit_submission_path(submission) %></td>
    <td><%= link_to 'Destroy', submission, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

app/views/submissions/edit.html.erb
<h1>Editing submission</h1>

<%= render 'form' %>

<%= link_to 'Show', @submission %> |
<%= link_to 'Back', submissions_path %>

app/views/submissions/index.html.erb
<div id="container">
  <% @submissions.each do |submission| %>
    <!--POST-->
    <div id="contents">
      <div class="blogentry">
        <h2>
          <%= link_to submission.title, url_with_protocol(submission.link), :target => :blank %>
        </h2>
        
        <p>
          <%= image_tag submission.photo.url(:thumb), class: 'thumb'%>
          <%= submission.blurb %>     
        </p>
        
      </div>
    </div>
  
  <!--END POST-->
  <% end %>
</div>

<script>
$(function(){
  $('#container').masonry({
    // options
    itemSelector : '#contents',
    columnWidth : 250px
  });
});

</script>

<!--MASONRY IMAGE LOAD FIX-->
<script>
  $(function(){

    var $container = $('#container');
  
    $container.imagesLoaded( function(){
      $container.masonry({
        itemSelector : '#contents'
      });
    });
  
  });
</script>

app/views/submissions/new.html.erb
<h1>New submission</h1>

<%= render 'form' %>

<%= link_to 'Back', submissions_path %>

app/views/submissions/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <b>Title:</b>
  <%= @submission.title %>
</p>

<p>
  <%= image_tag @submission.photo.url(:medium) %>
</p>

<p>
  <b>Blurb:</b>
  <%= @submission.blurb %>
</p>

<p>
  <b>Link:</b>
  <%= @submission.link %>
</p>


<%= link_to 'Edit', edit_submission_path(@submission) %> |
<%= link_to 'Back', submissions_path %>